### ISSUE TITLE
Automatically Device Offline

### ISSUE THREAD

**Issue by siddharaj9222** [XploitWizer/XploitSPY#5]
When User Clean Task Then Device Was Go Oflline

**Comment by siddharaj9222** [comment]
Automatically Device Offline After Some Time

**Comment by RaoMK** [comment]
> Automatically Device Offline After Some Time

It maybe due to some reasons like Data connection of device is turned off or some devices kill socket connection in locked screen so that why command queing feature in this app it automatically execute the command when device get online and collect the data automatically

**Comment by siddharaj9222** [comment]
Yes But Device Not Come Online I Tested 50 Times After Disconnect Device Not Come Online

**Comment by cool125** [comment]
> Yes But Device Not Come Online I Tested 50 Times After Disconnect Device Not Come Online
join me at telegram for discussion. id= time870

**Comment by RaoMK** [comment]
> Yes But Device Not Come Online I Tested 50 Times After Disconnect Device Not Come Online

can you tell us which device you are using because we tested it on multiple devices and not facing any such problem

**Comment by siddharaj9222** [comment]
Using Android pie

**Comment by RaoMK** [comment]
> Using Android pie

i am asking about brand name and model name of device not android version

**Comment by siddharaj9222** [comment]
mi note 5 pro
vivo v9 pro
mi 3s

**Comment by siddharaj9222** [comment]
use Administrator function
 So Device Never Go Offline

**Comment by chrisstone07** [comment]
Please do a git pull to get the updates, these issues have been fixed now.

**Comment by swapnil222-tikhe** [comment]
> Automatically Device Offline After Some Time

**Comment by swapnil222-tikhe** [comment]
I'm using MI Y1..Plz help.me to fix it

**Comment by kapil-signity** [comment]
Even after taking latest pull now still device offline . 
Device:- Redmi Xiomi Note 4
Activated all permission and backgroug battery optimized whitelisted already
given admin permission to application
still not showing in devices list
